export {
	type AgentRequirements,
	type AgentWallet,
	type ApiStatus,
	type ApiStatusResult,
	assertExchange,
	type BuilderConfig,
	calculateAssetId,
	clearAgentSessionAddress,
	createExchangeClient,
	createKey,
	type ExchangeMethod,
	type ExchangeParams,
	type ExchangeResponse,
	getAssetIdKind,
	getExplorerTokenUrl,
	getExplorerTxUrl,
	getMarketCapabilities,
	getReconnectDelayMs,
	HttpTransport,
	type HttpTransportOptions,
	type HyperliquidClients,
	type HyperliquidConfig,
	type HyperliquidContextValue,
	type HyperliquidEnv,
	HyperliquidProvider,
	type HyperliquidProviderProps,
	type HyperliquidQueryError,
	type InferData,
	type InferParams,
	type InferSubEvent,
	type InferSubListener,
	type InferSubParams,
	type InfoMethod,
	type InfoParams,
	type InfoResponse,
	type IRequestTransport,
	type ISubscriptionTransport,
	infoKey,
	infoKeys,
	infoQueryOptions,
	initializeClients,
	isBuilderPerpAssetId,
	isPerpAssetId,
	isPerpDelisted,
	isPerpOnlyIsolated,
	isSpotAssetId,
	type MarketCapabilities,
	MissingTransportError,
	MissingWalletError,
	type MutationParameter,
	type ParsedAssetId,
	type PerpDex,
	type Position,
	ProviderNotFoundError,
	parseAssetId,
	type QueryParameter,
	type RegistrationStatus,
	type RegistrationStep,
	readAgentFromStorage,
	readAgentSessionAddress,
	removeAgentFromStorage,
	type SubEvent,
	type SubMethod,
	type SubParams,
	type SubscriptionOptions,
	type SubscriptionResult,
	type SubscriptionStatus,
	serializeKey,
	subscriptionKeys,
	type TradingSession,
	type UseAgentRegistrationResult,
	type UseAgentStatusResult,
	type UseAgentWalletResult,
	type UserPositions,
	type UseUserWalletResult,
	useAgentRegistration,
	useAgentSessionAddress,
	useAgentWallet,
	useAgentWalletActions,
	useAgentWalletStorage,
	useApiStatus,
	useConfig,
	useExchange,
	useHttpTransport,
	useHyperliquid,
	useHyperliquidClients,
	useHyperliquidOptional,
	useHyperliquidStoreApi,
	useInfo,
	useSubscription,
	useSubscriptionTransport,
	useTradingSession,
	useUserWallet,
	type WebSocketStatus,
	WebSocketTransport,
	type WebSocketTransportOptions,
	WS_RELIABILITY_LIMITS,
	writeAgentSessionAddress,
	writeAgentToStorage,
} from "@hypeterminal/hl-react";
export type { MarketKind } from "@/domain/market";
// Paper-trading overrides: same API, but agent approval and positions are simulated locally.
export { useAgentStatus, useTradingGuard, useUserPositions } from "./paper-overrides";

import {
	getInfoClient as getInfoClientBase,
	getSubscriptionClient as getSubscriptionClientBase,
} from "@hypeterminal/hl-react";
import { isTestnet } from "@/lib/network";

export function getInfoClient() {
	return getInfoClientBase(isTestnet());
}

export function getSubscriptionClient() {
	return getSubscriptionClientBase(isTestnet());
}

export { MarketsInfoProvider } from "./hooks/MarketsInfoProvider";
export {
	type BuilderPerpMarketInfo,
	type BuilderPerpMarketsInfo,
	type PerpMarketInfo,
	type SpotMarketInfo,
	type UnifiedMarketInfo,
	type UseMarketsInfoReturn,
	useMarketsInfo,
	useSelectedMarketInfo,
} from "./hooks/useMarketsInfo";
export {
	type BuilderPerpMarket,
	type Markets,
	MarketsProvider,
	type PerpAsset,
	type PerpMarket,
	type SpotMarket,
	type SpotPair,
	type SpotToken,
	type UnifiedMarket,
	useMarkets,
} from "./markets";
export { chartSymbolFromMarket, getDexFromName, getMarketKindFromName } from "./markets/helper";
export { type UseSpotTokensReturn, useSpotTokens } from "./markets/use-spot-tokens";
export { type DepositStatus, type UseDepositResult, useDeposit } from "./use-deposit";
